### ISSUE TITLE
Will it auto-update on new AGH versions?

### ISSUE THREAD

**Issue by yourfriendaaron** [imTHAI/adguardhome-unbound-redis#3]
Hi,
This package looks great, thanks. Just wondering if it will auto-update on new AdGuard Home versions or if I'd need to wait for you personally to update it

**Comment by imTHAI** [comment]
Hello,

AGH should update by itself. It is the same daemon you would run on your linux or from their official docker container so it includes a binary autoupdate.
```
# /opt/AdGuardHome/AdGuardHome --help | grep update
  --update                           Update the current binary and restart the service in case it's installed.
```

The next time they're updated, I'll know for sure. ;-)

**Comment by imTHAI** [comment]
Did you get the bugs described in the 2 others issues ? 

I haven't been able to reproduce them and the docker works fine on my side, so I'd like to know if these are isolated cases.

**Comment by up2you1** [comment]
My instance is now showing as AdGuard Home v0.107.54 available,

wil update and report back,

**Comment by up2you1** [comment]
Hi, any luck with updating this? is there anything we need to do?

**Comment by imTHAI** [comment]
I'll push an update and I'll automate it on the release of next ADGH releases.

**Comment by imTHAI** [comment]
Voilà.
It is updated and now it will update as soon as a new version of ADGH is published.

Ideally, Adguardhome should be able to update itself without having to push and pull a new version of the adguard-home-unbound-redis image, which mean rebooting the container and emptying the redis cache.

**Comment by up2you1** [comment]
> Voilà. It is updated and now it will update as soon as a new version of ADGH is published.
> 
> Ideally, Adguardhome should be able to update itself without having to push and pull a new version of the adguard-home-unbound-redis image, which mean rebooting the container and emptying the redis cache.

Thank you, just updated via unraid :)

**Comment by up2you1** [comment]
Hi mate. AdGuard Home v0.107.55 is now available, doesn’t update for me via the gui.

**Comment by yourfriendaaron** [comment]
Correct me if I'm wrong, I'm an amateur on this stuff, but in general Docker containers should only really be updated by pushing new images from the host, correct, not from within the container?

**Comment by yourfriendaaron** [comment]
Update just came through on Unraid community app store, so it looks like @imTHAI's new process is working. Closing the issue.
